name: WardenBlocker
version: 1.0.1
main: org.wardenBlocker.wardenBlocker.WardenBlocker
api-version: 1.20
commands:
  wardenblocker:
    description: Reloads the WardenBlocker config
    usage: /wardenblocker reload
    permission: wardenblocker.reload

permissions:
  wardenblocker.reload:
    description: Allows reloading WardenBlocker config
    default: op